#!/usr/bin/env Rscript
d<-read.table("16_prop.tsv", header=T, sep="\t")
library(ggplot2)
library(scales)
png("mwt.png")
ggplot(d, aes(x=MWT)) + geom_histogram(aes(y=(..count..)/sum(..count..))) + scale_y_continuous(labels=percent_format()) + xlab("Molecular weight (g/mol)") + theme(axis.title.y = element_blank(), axis.title.x = element_text(size = 28), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
dev.off()
png("lgp.png")
ggplot(d, aes(x=LogP)) + geom_histogram(aes(y=(..count..)/sum(..count..))) + scale_y_continuous(labels=percent_format()) + xlab("Partition coefficient xlogP") + theme(axis.title.y = element_blank(), axis.title.x = element_text(size = 28), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
dev.off()
png("ads.png")
ggplot(d, aes(x=Desolv_apolar)) + geom_histogram(aes(y=(..count..)/sum(..count..))) + scale_y_continuous(labels=percent_format()) + xlab("Apolar desolvation (kcal/mol)") + theme(axis.title.y = element_blank(), axis.title.x = element_text(size = 28), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
dev.off()
png("pds.png")
ggplot(d, aes(x=Desolv_polar)) + geom_histogram(aes(y=(..count..)/sum(..count..))) + scale_y_continuous(labels=percent_format()) + xlab("Polar desolvation (kcal/mol)") + theme(axis.title.y = element_blank(), axis.title.x = element_text(size = 28), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
dev.off()
png("hbd.png")
ggplot(d, aes(x=factor(HBD))) + geom_histogram(aes(y=(..count..)/sum(..count..))) + scale_y_continuous(labels=percent_format()) + xlab("Hydrogen bond donors") + theme(axis.title.y = element_blank(), axis.title.x = element_text(size = 28), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
dev.off()
png("hba.png")
ggplot(d, aes(x=factor(HBA))) + geom_histogram(aes(y=(..count..)/sum(..count..))) + scale_y_continuous(labels=percent_format()) + xlab("Hydrogen bond acceptors") + theme(axis.title.y = element_blank(), axis.title.x = element_text(size = 28), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
dev.off()
png("psa.png")
ggplot(d, aes(x=tPSA)) + geom_histogram(aes(y=(..count..)/sum(..count..))) + scale_y_continuous(labels=percent_format()) + xlab("Polar surface area tPSA (A^2)") + theme(axis.title.y = element_blank(), axis.title.x = element_text(size = 28), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
dev.off()
png("chg.png")
ggplot(d, aes(x=factor(Charge))) + geom_histogram(aes(y=(..count..)/sum(..count..))) + scale_y_continuous(labels=percent_format()) + xlab("Net charge") + theme(axis.title.y = element_blank(), axis.title.x = element_text(size = 28), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
dev.off()
png("nrb.png")
ggplot(d, aes(x=factor(NRB))) + geom_histogram(aes(y=(..count..)/sum(..count..))) + scale_y_continuous(labels=percent_format()) + xlab("Rotatable bonds") + theme(axis.title.y = element_blank(), axis.title.x = element_text(size = 28), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20)) + scale_x_discrete(labels = c(0:10, "", "", "", "", 15, "", "", "", "", 20, "", "", "", "", 25, "", "", "", "", 30, "", "", "", "", 35))
